DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE TIPO_AUTOMOVIL CASCADE CONSTRAINTS;
DROP TABLE MODELO CASCADE CONSTRAINTS;
DROP TABLE MANTENCION CASCADE CONSTRAINTS;
DROP TABLE DETALLE_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE MECANICO CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE AUTOMOVIL CASCADE CONSTRAINTS;
DROP TABLE ESTANDAR CASCADE CONSTRAINTS;
DROP TABLE PREMIUM CASCADE CONSTRAINTS;

--Creacion de tablas
CREATE TABLE PAIS (
    id_pais         NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 9 INCREMENT BY 3),
    nom_pais        VARCHAR2 (30) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY (id_pais)
    )
;    

CREATE TABLE CIUDAD (
    id_ciudad       NUMBER(3) NOT NULL,
    nom_ciudad      VARCHAR2(30) NOT NULL,
    cod_pais        NUMBER (3) NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (id_ciudad),
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (cod_pais) REFERENCES PAIS (id_pais)
    )
;

CREATE TABLE SUCURSAL (
    id_sucursal     CHAR (3) NOT NULL,
    nom_sucursal    VARCHAR2(20) NOT NULL,
    calle           VARCHAR2(20) NOT NULL,
    num_calle       NUMBER(4) NOT NULL,
    cod_ciudad      NUMBER(3) NOT NULL,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (id_sucursal),
    CONSTRAINT FK_SUCURSAL_CIUDAD FOREIGN KEY (cod_ciudad) REFERENCES CIUDAD (id_ciudad)
    )
;    

CREATE TABLE MARCA (
    id_marca        NUMBER(2) NOT NULL,
    descripcion     VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY (id_marca)
    )
;

CREATE TABLE MODELO (
    id_modelo       NUMBER(5) NOT NULL,
    marca_id        NUMBER(2) NOT NULL,
    descripcion     VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MODELO PRIMARY KEY (id_modelo, marca_id),
    CONSTRAINT FK_MODELO_MARCA FOREIGN KEY (marca_id) REFERENCES MARCA (id_marca)
    )
;

CREATE TABLE TIPO_AUTOMOVIL (
    id_tipo         CHAR(3) NOT NULL,
    descripcion     VARCHAR2(20),
    CONSTRAINT PK_TIPO_AUTOMOVIL PRIMARY KEY (id_tipo)
    )
;

CREATE TABLE CLIENTE (
    rut             NUMBER(8) NOT NULL,
    dv              CHAR(1) NOT NULL,
    pnombre         VARCHAR2(20) NOT NULL,
    snombre         VARCHAR2(20),
    apaterno        VARCHAR2(20) NOT NULL,
    amaterno        VARCHAR2(20) NOT NULL,
    telefono        VARCHAR2(12),
    email           VARCHAR2(40),
    tipo_cli        CHAR(1),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (rut)
    )
;

CREATE TABLE MECANICO (
    cod_mecanico    NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 460 INCREMENT BY 7),
    pnombre         VARCHAR2(20) NOT NULL,
    snombre         VARCHAR2(20) NOT NULL,
    apaterno        VARCHAR2(20) NOT NULL,
    amaterno        VARCHAR2(20) NOT NULL, 
    bono_jefatura   NUMBER(10),
    sueldo          NUMBER(10) NOT NULL,
    monto_impuestos NUMBER(10) NOT NULL,
    cod_supervisor  NUMBER(5),
    CONSTRAINT PK_MECANICO PRIMARY KEY (cod_mecanico),
    CONSTRAINT FK_MECANICO_MECANICO FOREIGN KEY (cod_supervisor) REFERENCES MECANICO (cod_mecanico)
    )
;    

CREATE TABLE SERVICIO (
    id_servicio     NUMBER(3) NOT NULL,
    descripcion     VARCHAR2(100) NOT NULL,
    costo           NUMBER(7) NOT NULL,
    CONSTRAINT PK_SERVICIO PRIMARY KEY (id_servicio)
    )
;    

CREATE TABLE AUTOMOVIL (
    patente         CHAR(8) NOT NULL,
    annio           NUMBER(4) NOT NULL,
    cant_puertas    NUMBER(1) NOT NULL,
    km              NUMBER(6) NOT NULL,
    color           VARCHAR2(30) NOT NULL,
    cod_tipo_auto   CHAR(3) NOT NULL,
    cod_modelo      NUMBER(5) NOT NULL,
    cod_marca       NUMBER(2) NOT NULL,
    cl_rut          NUMBER(8) NOT NULL,
    CONSTRAINT PK_AUTOMOVIL PRIMARY KEY (patente),
    CONSTRAINT FK_AUTOMOVIL_CLIENTE FOREIGN KEY (cl_rut) REFERENCES CLIENTE (rut),
    CONSTRAINT FK_AUTOMOVIL_MODELO FOREIGN KEY (cod_modelo, cod_marca) REFERENCES MODELO (id_modelo, marca_id),
    CONSTRAINT FK_AUTOMOVIL_TIPO FOREIGN KEY (cod_tipo_auto) REFERENCES TIPO_AUTOMOVIL (id_tipo)
    )
;


CREATE TABLE MANTENCION (
    num_mantencion  NUMBER(4) NOT NULL,
    cod_sucursal    CHAR(3) NOT NULL,
    fecha_ingreso   DATE NOT NULL,
    fecha_salida    DATE,
    patente_auto    CHAR(8),
    cod_mecanico    NUMBER(5) NOT NULL,
    costo_total     NUMBER(7) NOT NULL,
    estado          VARCHAR2(15),
    CONSTRAINT PK_MANTENCION PRIMARY KEY (num_mantencion),
    CONSTRAINT FK_MANT_AUTOMOVIL FOREIGN KEY (patente_auto) REFERENCES AUTOMOVIL (patente),
    CONSTRAINT FK_MANT_MECANICO FOREIGN KEY (cod_mecanico) REFERENCES MECANICO (cod_mecanico),
    CONSTRAINT FK_MANT_SUCURSAL FOREIGN KEY (cod_sucursal) REFERENCES SUCURSAL (id_sucursal)
    )
;    

CREATE TABLE DETALLE_SERVICIO (
    mantencion_num  NUMBER(4) NOT NULL,
    cod_servicio    NUMBER(3) NOT NULL,
    descuento_serv  NUMBER(4,3) NOT NULL,
    cantidad        NUMBER(3) NOT NULL,
    CONSTRAINT PK_DETALLE_SERVICIO PRIMARY KEY (mantencion_num, cod_servicio),
    CONSTRAINT FK_DET_SERV_MANTENCION FOREIGN KEY (mantencion_num) REFERENCES MANTENCION (num_mantencion),
    CONSTRAINT FK_DET_SERV_SERVICIO FOREIGN KEY (cod_servicio) REFERENCES SERVICIO (id_servicio)
    )
;    

CREATE TABLE ESTANDAR (
    cl_rut              NUMBER(8) NOT NULL,
    puntaje_fidelidad   NUMBER(10) NOT NULL,
    CONSTRAINT PK_NORMAL PRIMARY KEY (cl_rut),
    CONSTRAINT FK_NORMAL_CLIENTE FOREIGN KEY (cl_rut) REFERENCES CLIENTE (rut)
    )
;

CREATE TABLE PREMIUM (
    cl_rut              NUMBER(8) NOT NULL,
    pesos_clientes      NUMBER(10) NOT NULL,
    monto_credito       NUMBER(10),
    CONSTRAINT PK_PREMIUM PRIMARY KEY (cl_rut),
    CONSTRAINT FK_PREMIUM_CLIENTE FOREIGN KEY (cl_rut) REFERENCES CLIENTE (rut)
    )
;
--Fin de creacion de tablas

--Inicio alteracion de tablas
ALTER TABLE MANTENCION
DROP COLUMN costo_total;

ALTER TABLE DETALLE_SERVICIO
DROP CONSTRAINT FK_DET_SERV_MANTENCION;

ALTER TABLE MANTENCION
DROP CONSTRAINT PK_MANTENCION;

ALTER TABLE MANTENCION 
ADD CONSTRAINT PK_MANTENCION PRIMARY KEY (num_mantencion, cod_sucursal);

SELECT * FROM MANTENCION;

ALTER TABLE DETALLE_SERVICIO
ADD cod_sucursal CHAR(3);

ALTER TABLE DETALLE_SERVICIO
ADD CONSTRAINT FK_DET_SERV_MANTENCION FOREIGN KEY (mantencion_num, cod_sucursal) REFERENCES MANTENCION (num_mantencion, cod_sucursal);

SELECT * FROM DETALLE_SERVICIO;

ALTER TABLE CLIENTE
ADD CONSTRAINT UQ_EMAIL_CLIENTE UNIQUE (email);

SELECT * FROM CLIENTE;

ALTER TABLE CLIENTE
ADD CONSTRAINT CK_CLIENTE_DV CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE MECANICO
ADD CONSTRAINT CK_SUELDO_MECANICO CHECK (SUELDO >= 510000);

ALTER TABLE MANTENCION
ADD CONSTRAINT CK_ESTADO_MANTENCION CHECK (estado IN ('RESERVA', 'INGRESADO', 'ENTREGADO', 'ANULADO'));
--Fin alteracion tablas

--Inico poblamiento tablas
DROP SEQUENCE seq_servicio;
CREATE SEQUENCE seq_servicio
START WITH 400 INCREMENT BY 2;

DROP SEQUENCE seq_ciudad;
CREATE SEQUENCE seq_ciudad
START WITH 165 INCREMENT BY 5;

--Inicio mecanicos
SELECT * FROM MECANICO;
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jorge', 'Pablo', 'Soto', 'Sierpe', 5400000, 2759000, 223580, NULL);
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Sandra', 'Josefa', 'Letelier', 'S.', 0, 659000, 22358, 460);

INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jose', 'Miguel', 'Troncoso', 'B.', NULL, 659000, 44580, 474);
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Juan', 'Pablo', 'Sánchez', 'R.', NULL, 859000, 23380, 474);

INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Carlos', 'Felipe', 'Soto', 'J.', 0, 597000, 23580, 474);
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alberto', 'P.', 'Cerda', 'Ramírez', NULL, 559000, 22380, 460);
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alejandra', 'Gabriela', 'Infanti', 'R.', NULL, 659000, 22380, 460);
INSERT INTO MECANICO (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Roberto', 'Patricio', 'Gutierrez', 'Sosa', NULL, 859000, 22380, 460);
--Fin mecanicos
--Inicio pais
SELECT * FROM PAIS;
INSERT INTO PAIS (nom_pais) VALUES ('Chile');
INSERT INTO PAIS (nom_pais) VALUES ('Perú');
INSERT INTO PAIS (nom_pais) VALUES ('Colombia');
--Fin pais
--Inicio ciudad
SELECT * FROM CIUDAD;
INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais) VALUES (seq_ciudad.NEXTVAL, 'Santiago', 9);
INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais) VALUES (seq_ciudad.NEXTVAL, 'Lima', 12);
INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais) VALUES (seq_ciudad.NEXTVAL, 'Bogota', 15);
--Fin ciudad
--Inicio servicio
SELECT * FROM SERVICIO;
INSERT INTO SERVICIO (id_servicio, descripcion, costo) VALUES (seq_servicio.NEXTVAL, 'Cambio de luces', 45000);
INSERT INTO SERVICIO (id_servicio, descripcion, costo) VALUES (seq_servicio.NEXTVAL, 'Desabolladura', 67000);
INSERT INTO SERVICIO (id_servicio, descripcion, costo) VALUES (seq_servicio.NEXTVAL, 'Revisión de frenos', 30000);
INSERT INTO SERVICIO (id_servicio, descripcion, costo) VALUES (seq_servicio.NEXTVAL, 'Cambio de puerta trasera', 50000);
--Fin servicio
--Inicio sucursal
SELECT * FROM SUCURSAL;
INSERT INTO SUCURSAL (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES ('S01', 'Providencia', 'Av. A. Varas', 234, 165);
INSERT INTO SUCURSAL (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES ('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);
INSERT INTO SUCURSAL (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES ('S03', 'El cafetero', 'Av. El Faro', 900, 175);
--Fin sucursal
--Inicio mantencion
SELECT * FROM MANTENCION;
INSERT INTO MANTENCION (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (101, 'S01', TO_DATE('12-04-2023','DD-MM-YYYY'), NULL, NULL, 481, 'RESERVA');
INSERT INTO MANTENCION (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (102, 'S02', TO_DATE('21-02-2023','DD-MM-YYYY'), TO_DATE('21-02-2023', 'DD-MM-YYYY'), NULL, 502, 'ENTREGADO');
INSERT INTO MANTENCION (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (103, 'S02', TO_DATE('09-10-2023','DD-MM-YYYY'), NULL, NULL, 502, 'ANULADO');
INSERT INTO MANTENCION (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (104, 'S03', TO_DATE('11-08-2023','DD-MM-YYYY'), TO_DATE('18-08-2023', 'DD-MM-YYYY'), NULL, 509, 'ENTREGADO');
INSERT INTO MANTENCION (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (105, 'S03', TO_DATE('03-12-2023','DD-MM-YYYY'), NULL, NULL, 509, 'INGRESADO');
--Fin mantencion
--Inicio selects para recuperacion de datos
SELECT * FROM MECANICO;
SELECT * FROM PAIS;
SELECT * FROM CIUDAD;
SELECT * FROM SERVICIO;
SELECT * FROM SUCURSAL;
SELECT * FROM MANTENCION;

--Informe 1
SELECT
    cod_mecanico AS "ID MECANICO",
    pnombre || ' ' || apaterno AS "NOMBRE MECANICO",
    sueldo AS "SALARIO",
    monto_impuestos AS "IMPUESTO ACTUAL",
    monto_impuestos * 0.8 AS "IMPUESTO REBAJADO",
    sueldo - (monto_impuestos * 0.8) AS "SUELDO CON REBAJA DE IMPUESTOS"
FROM mecanico
WHERE bono_jefatura IS NULL AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;

--Informe 2
SELECT
    cod_mecanico AS "IDENTIFICADOR",
    pnombre || ' ' || snombre || ' ' || apaterno AS "MECANICO",
    sueldo AS "SALARIO ACTUAL",
    sueldo * 0.05 AS "AJUSTE",
    sueldo + (sueldo * 0.05) AS "SUELDO REAJUSTADO"
FROM mecanico
WHERE sueldo BETWEEN 600000 AND 900000 OR cod_supervisor IS NULL
ORDER BY sueldo ASC, 
    pnombre || ' ' || snombre || ' ' || apaterno DESC;
--Fin selects
COMMIT;











