--Creación de usuario
CREATE USER PRY2204_S8 IDENTIFIED BY "Contraseña_Nueva1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER PRY2204_S8 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO PRY2204_S8;
GRANT "RESOURCE" TO PRY2204_S8;
ALTER USER PRY2204_S8 DEFAULT ROLE "RESOURCE";

--DROP USER PRY2204_S8;